name: Bouncer
main: com.minecarts.bouncer.Bouncer
version: ${pom.version}
website: http://minecarts.com
author: Verrier
depend: [DBQuery, ObjectData, BarrensChat]
description: >
             A player connection and disconnection support plugin
commands:
    bouncer:
        description: Access to the bouncer functions
        usage: /<command>
    stop:
        aliases: [shutdown, restart]
        description: Stop or restart the server gracefully
        usage: /<command> [now | time in minutes]
    ban:
        description: Ban players from the server
        usage: /<command> name [time] [reason]
    kick:
        description: Kick players from the server
        usage: /<command> name [reason]
permissions:
    bouncer.stealth_mode:
        description: "Do not display the login / logout messages for this user"
        default: false
    bouncer.admin:
        description: "Administrative command access to bouncer"
        default: op
    bouncer.stop:
        description: "Ability to gracefully stop the server"
        default: op
    bouncer.ban:
        description: "Ability to ban players from the server"
        default: op
    bouncer.kick:
        description: "Ability to kick players from the server"
        default: op
    