name: Bouncer
main: com.minecarts.bouncer.Bouncer
version: ${pom.version}
website: http://minecarts.com
author: Verrier
depend: [DBConnector, ObjectData, BarrensChat]
description: >
             A player connection and disconnection support plugin
commands:
  bouncer:
    description: Access to the bouncer functions
    usage: /<command>
    