name: Template Plugin
main: com.minecarts.templateplugin.TemplatePlugin
version: 1.0.0
website: http://minecarts.com
author: Verrier
description: >
             A description of your plugin
commands:
  test:
    description: Do the test feature!
    usage: /<command>