name: Bouncer
main: com.minecarts.bouncer.Bouncer
version: 1.0.1
website: http://minecarts.com
author: Verrier
depend: [DBConnector, ObjectData]
description: >
             A player connection and disconnection support plugin
commands:
  bouncer:
    description: Access to the bouncer functions
    usage: /<command>
    